import { query } from "../../_generated/server";
import { v } from "convex/values";

export const getTenantHealthScores = query({
  args: {
    sessionToken: v.string(),
    tenantId: v.optional(v.string()),
    category: v.optional(v.union(
      v.literal("adoption"),
      v.literal("engagement"),
      v.literal("support"),
      v.literal("technical"),
      v.literal("financial"),
      v.literal("overall")
    )),
    timeRange: v.optional(v.union(v.literal("30d"), v.literal("90d"), v.literal("180d"), v.literal("365d"))),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // TODO: Implement tenant health scores retrieval
    return [
      {
        _id: "health_1",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        category: "overall",
        score: 87.5,
        grade: "B",
        metrics: {
          adoption: 92.3,
          engagement: 85.7,
          support: 78.9,
          technical: 91.2,
          financial: 88.4,
        },
        factors: [
          {
            name: "User Adoption Rate",
            weight: 0.25,
            value: 92.3,
            impact: "High adoption of core features indicates successful onboarding",
          },
          {
            name: "Daily Active Users",
            weight: 0.20,
            value: 85.7,
            impact: "Good engagement levels with consistent daily usage",
          },
          {
            name: "Support Ticket Volume",
            weight: 0.15,
            value: 78.9,
            impact: "Moderate support needs indicate room for improvement",
          },
          {
            name: "System Performance",
            weight: 0.20,
            value: 91.2,
            impact: "Excellent technical performance with minimal downtime",
          },
          {
            name: "Payment Timeliness",
            weight: 0.20,
            value: 88.4,
            impact: "Good financial health with timely payments",
          },
        ],
        recommendations: [
          "Implement proactive user training to increase engagement",
          "Create self-service help resources to reduce support volume",
          "Develop advanced feature adoption campaigns",
          "Schedule regular system health check-ins",
        ],
        trends: [
          { date: "2024-01-01", score: 82.3 },
          { date: "2024-02-01", score: 84.1 },
          { date: "2024-03-01", score: 86.7 },
          { date: "2024-04-01", score: 87.5 },
        ],
        calculatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
        calculatedBy: "success_manager@edumyles.com",
        previousScore: 86.7,
        scoreChange: 0.8,
      },
      {
        _id: "health_2",
        tenantId: "tenant_2",
        tenantName: "Mombasa International School",
        category: "overall",
        score: 91.8,
        grade: "A",
        metrics: {
          adoption: 95.7,
          engagement: 93.2,
          support: 89.5,
          technical: 94.1,
          financial: 92.8,
        },
        factors: [
          {
            name: "User Adoption Rate",
            weight: 0.25,
            value: 95.7,
            impact: "Exceptional adoption across all user groups",
          },
          {
            name: "Daily Active Users",
            weight: 0.20,
            value: 93.2,
            impact: "Outstanding engagement with high daily usage",
          },
          {
            name: "Support Ticket Volume",
            weight: 0.15,
            value: 89.5,
            impact: "Low support needs indicate high user satisfaction",
          },
          {
            name: "System Performance",
            weight: 0.20,
            value: 94.1,
            impact: "Superior technical performance with excellent uptime",
          },
          {
            name: "Payment Timeliness",
            weight: 0.20,
            value: 92.8,
            impact: "Excellent financial health with consistent payments",
          },
        ],
        recommendations: [
          "Maintain current success strategies",
          "Share best practices with other tenants",
          "Consider advanced feature adoption",
          "Explore expansion opportunities",
        ],
        trends: [
          { date: "2024-01-01", score: 88.2 },
          { date: "2024-02-01", score: 89.7 },
          { date: "2024-03-01", score: 90.5 },
          { date: "2024-04-01", score: 91.8 },
        ],
        calculatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
        calculatedBy: "success_manager@edumyles.com",
        previousScore: 90.5,
        scoreChange: 1.3,
      },
      {
        _id: "health_3",
        tenantId: "tenant_3",
        tenantName: "Kisumu High School",
        category: "overall",
        score: 76.2,
        grade: "C",
        metrics: {
          adoption: 78.5,
          engagement: 72.3,
          support: 65.8,
          technical: 81.9,
          financial: 79.4,
        },
        factors: [
          {
            name: "User Adoption Rate",
            weight: 0.25,
            value: 78.5,
            impact: "Moderate adoption with room for improvement",
          },
          {
            name: "Daily Active Users",
            weight: 0.20,
            value: 72.3,
            impact: "Low engagement levels require attention",
          },
          {
            name: "Support Ticket Volume",
            weight: 0.15,
            value: 65.8,
            impact: "High support volume indicates usability issues",
          },
          {
            name: "System Performance",
            weight: 0.20,
            value: 81.9,
            impact: "Good technical performance with occasional issues",
          },
          {
            name: "Payment Timeliness",
            weight: 0.20,
            value: 79.4,
            impact: "Fair financial health with some delays",
          },
        ],
        recommendations: [
          "Implement comprehensive user training program",
          "Address technical issues causing high support volume",
          "Create engagement campaigns to increase daily usage",
          "Review and optimize user onboarding process",
          "Provide financial management support",
        ],
        trends: [
          { date: "2024-01-01", score: 74.1 },
          { date: "2024-02-01", score: 75.3 },
          { date: "2024-03-01", score: 75.8 },
          { date: "2024-04-01", score: 76.2 },
        ],
        calculatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
        calculatedBy: "success_manager@edumyles.com",
        previousScore: 75.8,
        scoreChange: 0.4,
      },
    ];
  },
});

export const getSuccessInitiatives = query({
  args: {
    sessionToken: v.string(),
    tenantId: v.optional(v.string()),
    status: v.optional(v.union(v.literal("planned"), v.literal("active"), v.literal("completed"), v.literal("cancelled"))),
    category: v.optional(v.union(
      v.literal("onboarding"),
      v.literal("training"),
      v.literal("optimization"),
      v.literal("support"),
      v.literal("engagement"),
      v.literal("retention")
    )),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // TODO: Implement success initiatives retrieval
    return [
      {
        _id: "initiative_1",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        title: "Advanced Features Adoption Campaign",
        description: "Comprehensive initiative to increase adoption of advanced platform features including analytics, automation, and integrations",
        category: "engagement",
        priority: "high",
        targetScore: 95.0,
        currentScore: 78.5,
        progress: 82.6,
        actions: [
          {
            id: "action_1",
            title: "Create training materials for advanced features",
            description: "Develop comprehensive documentation and video tutorials",
            assignee: "training_team@edumyles.com",
            dueDate: Date.now() + 7 * 24 * 60 * 60 * 1000,
            status: "completed",
            completedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
          },
          {
            id: "action_2",
            title: "Conduct webinars on advanced features",
            description: "Host live training sessions for power users",
            assignee: "success_manager@edumyles.com",
            dueDate: Date.now() + 14 * 24 * 60 * 60 * 1000,
            status: "in_progress",
            completedAt: null,
          },
          {
            id: "action_3",
            title: "Create feature adoption dashboard",
            description: "Build dashboard to track feature usage metrics",
            assignee: "analytics_team@edumyles.com",
            dueDate: Date.now() + 21 * 24 * 60 * 60 * 1000,
            status: "pending",
            completedAt: null,
          },
        ],
        milestones: [
          {
            id: "milestone_1",
            title: "Training materials completed",
            description: "All documentation and tutorials ready",
            targetDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
            completed: true,
            completedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
          },
          {
            id: "milestone_2",
            title: "First webinar conducted",
            description: "Initial training session completed",
            targetDate: Date.now() + 10 * 24 * 60 * 60 * 1000,
            completed: false,
            completedAt: null,
          },
          {
            id: "milestone_3",
            title: "50% feature adoption achieved",
            description: "Half of target users adopting advanced features",
            targetDate: Date.now() + 30 * 24 * 60 * 60 * 1000,
            completed: false,
            completedAt: null,
          },
        ],
        createdBy: "success_manager@edumyles.com",
        assignedTo: "success_manager@edumyles.com",
        startDate: Date.now() - 14 * 24 * 60 * 60 * 1000,
        targetDate: Date.now() + 45 * 24 * 60 * 60 * 1000,
        status: "active",
        createdAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
      },
      {
        _id: "initiative_2",
        tenantId: "tenant_3",
        tenantName: "Kisumu High School",
        title: "User Engagement Improvement Program",
        description: "Targeted program to increase daily active users and improve overall platform engagement",
        category: "engagement",
        priority: "high",
        targetScore: 85.0,
        currentScore: 72.3,
        progress: 65.8,
        actions: [
          {
            id: "action_4",
            title: "Analyze current usage patterns",
            description: "Identify barriers to engagement",
            assignee: "analytics_team@edumyles.com",
            dueDate: Date.now() - 7 * 24 * 60 * 60 * 1000,
            status: "completed",
            completedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
          },
          {
            id: "action_5",
            title: "Implement gamification features",
            description: "Add achievement system and progress tracking",
            assignee: "product_team@edumyles.com",
            dueDate: Date.now() + 21 * 24 * 60 * 60 * 1000,
            status: "in_progress",
            completedAt: null,
          },
          {
            id: "action_6",
            title: "Launch engagement campaign",
            description: "Email and in-app notifications to encourage usage",
            assignee: "marketing_team@edumyles.com",
            dueDate: Date.now() + 14 * 24 * 60 * 60 * 1000,
            status: "pending",
            completedAt: null,
          },
        ],
        milestones: [
          {
            id: "milestone_4",
            title: "Usage analysis completed",
            description: "Barriers to engagement identified",
            targetDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
            completed: true,
            completedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
          },
          {
            id: "milestone_5",
            title: "Gamification features launched",
            description: "Achievement system live",
            targetDate: Date.now() + 20 * 24 * 60 * 60 * 1000,
            completed: false,
            completedAt: null,
          },
          {
            id: "milestone_6",
            title: "75% engagement target reached",
            description: "Daily active users increased to target level",
            targetDate: Date.now() + 60 * 24 * 60 * 60 * 1000,
            completed: false,
            completedAt: null,
          },
        ],
        createdBy: "success_manager@edumyles.com",
        assignedTo: "success_manager@edumyles.com",
        startDate: Date.now() - 21 * 24 * 60 * 60 * 1000,
        targetDate: Date.now() + 60 * 24 * 60 * 60 * 1000,
        status: "active",
        createdAt: Date.now() - 21 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
      },
      {
        _id: "initiative_3",
        tenantId: "tenant_2",
        tenantName: "Mombasa International School",
        title: "Support Optimization Initiative",
        description: "Reduce support ticket volume through improved documentation and self-service resources",
        category: "support",
        priority: "medium",
        targetScore: 95.0,
        currentScore: 89.5,
        progress: 94.2,
        actions: [
          {
            id: "action_7",
            title: "Create comprehensive help center",
            description: "Build detailed documentation and FAQs",
            assignee: "content_team@edumyles.com",
            dueDate: Date.now() - 14 * 24 * 60 * 60 * 1000,
            status: "completed",
            completedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
          },
          {
            id: "action_8",
            title: "Implement chatbot support",
            description: "Add AI-powered chatbot for common questions",
            assignee: "tech_team@edumyles.com",
            dueDate: Date.now() - 7 * 24 * 60 * 60 * 1000,
            status: "completed",
            completedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
          },
          {
            id: "action_9",
            title: "Train support team on new resources",
            description: "Ensure support team can effectively guide users to self-service",
            assignee: "support_manager@edumyles.com",
            dueDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
            status: "completed",
            completedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
          },
        ],
        milestones: [
          {
            id: "milestone_7",
            title: "Help center launched",
            description: "Comprehensive documentation available",
            targetDate: Date.now() - 10 * 24 * 60 * 60 * 1000,
            completed: true,
            completedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
          },
          {
            id: "milestone_8",
            title: "Chatbot deployed",
            description: "AI-powered support available 24/7",
            targetDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
            completed: true,
            completedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
          },
          {
            id: "milestone_9",
            title: "Support tickets reduced by 30%",
            description: "Target reduction in support volume achieved",
            targetDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
            completed: true,
            completedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
          },
        ],
        createdBy: "success_manager@edumyles.com",
        assignedTo: "support_manager@edumyles.com",
        startDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
        targetDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
        status: "completed",
        createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
      },
    ];
  },
});

export const getSuccessMetrics = query({
  args: {
    sessionToken: v.string(),
    tenantId: v.optional(v.string()),
    category: v.optional(v.union(
      v.literal("adoption"),
      v.literal("engagement"),
      v.literal("support"),
      v.literal("technical"),
      v.literal("financial")
    )),
    isActive: v.optional(v.boolean()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // TODO: Implement success metrics retrieval
    return [
      {
        _id: "metric_1",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        name: "User Adoption Rate",
        description: "Percentage of active users who have adopted core platform features",
        category: "adoption",
        unit: "%",
        targetValue: 95.0,
        currentValue: 92.3,
        baselineValue: 75.0,
        calculationMethod: "automated",
        frequency: "weekly",
        isActive: true,
        trend: "increasing",
        lastUpdated: Date.now() - 3 * 24 * 60 * 60 * 1000,
        history: [
          { date: "2024-01-01", value: 78.5 },
          { date: "2024-01-08", value: 81.2 },
          { date: "2024-01-15", value: 84.7 },
          { date: "2024-01-22", value: 87.3 },
          { date: "2024-01-29", value: 89.8 },
          { date: "2024-02-05", value: 91.5 },
          { date: "2024-02-12", value: 92.3 },
        ],
        createdBy: "success_manager@edumyles.com",
        createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
      },
      {
        _id: "metric_2",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        name: "Daily Active Users",
        description: "Number of unique users accessing the platform daily",
        category: "engagement",
        unit: "users",
        targetValue: 850,
        currentValue: 728,
        baselineValue: 450,
        calculationMethod: "automated",
        frequency: "daily",
        isActive: true,
        trend: "increasing",
        lastUpdated: Date.now() - 1 * 24 * 60 * 60 * 1000,
        history: [
          { date: "2024-02-10", value: 695 },
          { date: "2024-02-11", value: 712 },
          { date: "2024-02-12", value: 728 },
          { date: "2024-02-13", value: 735 },
          { date: "2024-02-14", value: 742 },
        ],
        createdBy: "success_manager@edumyles.com",
        createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
      },
      {
        _id: "metric_3",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        name: "Support Ticket Volume",
        description: "Number of support tickets created per week",
        category: "support",
        unit: "tickets",
        targetValue: 15,
        currentValue: 22,
        baselineValue: 45,
        calculationMethod: "automated",
        frequency: "weekly",
        isActive: true,
        trend: "decreasing",
        lastUpdated: Date.now() - 2 * 24 * 60 * 60 * 1000,
        history: [
          { date: "2024-01-15", value: 38 },
          { date: "2024-01-22", value: 35 },
          { date: "2024-01-29", value: 31 },
          { date: "2024-02-05", value: 28 },
          { date: "2024-02-12", value: 25 },
          { date: "2024-02-19", value: 22 },
        ],
        createdBy: "success_manager@edumyles.com",
        createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
      },
      {
        _id: "metric_4",
        tenantId: "tenant_2",
        tenantName: "Mombasa International School",
        name: "User Satisfaction Score",
        description: "Average user satisfaction rating from surveys",
        category: "engagement",
        unit: "score",
        targetValue: 4.5,
        currentValue: 4.3,
        baselineValue: 3.8,
        calculationMethod: "survey",
        frequency: "monthly",
        isActive: true,
        trend: "increasing",
        lastUpdated: Date.now() - 15 * 24 * 60 * 60 * 1000,
        history: [
          { date: "2023-11-01", value: 3.9 },
          { date: "2023-12-01", value: 4.1 },
          { date: "2024-01-01", value: 4.2 },
          { date: "2024-02-01", value: 4.3 },
        ],
        createdBy: "success_manager@edumyles.com",
        createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
      },
    ];
  },
});

export const getTenantSuccessOverview = query({
  args: {
    sessionToken: v.string(),
    timeRange: v.optional(v.union(v.literal("30d"), v.literal("90d"), v.literal("180d"), v.literal("365d"))),
  },
  handler: async (ctx, args) => {
    const timeRange = args.timeRange || "90d";
    
    // TODO: Implement tenant success overview calculation
    return {
      overview: {
        totalTenants: 156,
        activeTenants: 142,
        averageHealthScore: 83.7,
        gradeDistribution: {
          A: 45,
          B: 67,
          C: 28,
          D: 12,
          F: 4,
        },
        totalInitiatives: 89,
        activeInitiatives: 34,
        completedInitiatives: 45,
        averageInitiativeProgress: 72.4,
      },
      trends: {
        healthScores: [
          { date: "2024-01-01", score: 81.2 },
          { date: "2024-02-01", score: 82.5 },
          { date: "2024-03-01", score: 83.1 },
          { date: "2024-04-01", score: 83.7 },
        ],
        initiativeCompletions: [
          { date: "2024-01-01", completed: 8 },
          { date: "2024-02-01", completed: 12 },
          { date: "2024-03-01", completed: 15 },
          { date: "2024-04-01", completed: 10 },
        ],
        engagementMetrics: [
          { date: "2024-01-01", adoption: 78.5, engagement: 71.2 },
          { date: "2024-02-01", adoption: 81.3, engagement: 74.8 },
          { date: "2024-03-01", adoption: 84.1, engagement: 78.5 },
          { date: "2024-04-01", adoption: 86.7, engagement: 81.9 },
        ],
      },
      topPerformers: {
        tenants: [
          {
            tenantId: "tenant_2",
            tenantName: "Mombasa International School",
            healthScore: 91.8,
            grade: "A",
            initiativesCompleted: 8,
            trend: "improving",
          },
          {
            tenantId: "tenant_5",
            tenantName: "Eldoret Academy",
            healthScore: 89.4,
            grade: "B",
            initiativesCompleted: 6,
            trend: "stable",
          },
          {
            tenantId: "tenant_8",
            tenantName: "Nakuru High School",
            healthScore: 87.9,
            grade: "B",
            initiativesCompleted: 7,
            trend: "improving",
          },
        ],
        initiatives: [
          {
            initiativeId: "initiative_3",
            title: "Support Optimization Initiative",
            tenantName: "Mombasa International School",
            progress: 94.2,
            impact: "Reduced support tickets by 30%",
            category: "support",
          },
          {
            initiativeId: "initiative_7",
            title: "User Training Program",
            tenantName: "Eldoret Academy",
            progress: 88.5,
            impact: "Increased feature adoption by 25%",
            category: "training",
          },
          {
            initiativeId: "initiative_12",
            title: "Engagement Campaign",
            tenantName: "Nakuru High School",
            progress: 82.1,
            impact: "Daily active users increased by 40%",
            category: "engagement",
          },
        ],
      },
      atRiskTenants: [
        {
          tenantId: "tenant_3",
          tenantName: "Kisumu High School",
          healthScore: 76.2,
          grade: "C",
          riskFactors: ["Low engagement", "High support volume", "Payment delays"],
          recommendedActions: ["Training program", "Support optimization", "Financial review"],
        },
        {
          tenantId: "tenant_11",
          tenantName: "Thika Girls School",
          healthScore: 71.8,
          grade: "C",
          riskFactors: ["Declining adoption", "Technical issues", "Low satisfaction"],
          recommendedActions: ["Technical audit", "User training", "Feature optimization"],
        },
      ],
      categoryBreakdown: [
        {
          category: "adoption",
          averageScore: 85.3,
          trend: "improving",
          keyDrivers: ["Training programs", "Feature improvements", "User support"],
        },
        {
          category: "engagement",
          averageScore: 79.8,
          trend: "stable",
          keyDrivers: ["Gamification", "Content relevance", "User experience"],
        },
        {
          category: "support",
          averageScore: 81.4,
          trend: "improving",
          keyDrivers: ["Self-service resources", "Chatbot support", "Documentation"],
        },
        {
          category: "technical",
          averageScore: 88.7,
          trend: "stable",
          keyDrivers: ["System stability", "Performance optimization", "Uptime"],
        },
        {
          category: "financial",
          averageScore: 84.2,
          trend: "stable",
          keyDrivers: ["Payment processing", "Billing clarity", "Cost optimization"],
        },
      ],
    };
  },
});
